### ISSUE TITLE
Importing css or scss file no longer possible

### ISSUE THREAD

**Issue by richmonkeys** [SolidZORO/next-plugin-antd-less#1]
Error `CSS Modules cannot be imported from within node_modules.` when trying to import css or scss file directly in jsx components.
```typescript
import styles from './DefaultLayout.module.scss'
```

The code causing this:
https://github.com/SolidZORO/next-plugin-antd-less/blob/4991a3ed4324c0bafb721bd50b45d33c0c631b71/index.js#L93

I think we are supposed to insert the lessModule instead of replacing sassModule with it, in order to existing sass loader and it's features.

Proposed fixed:
```typescript
rules[1].oneOf.splice(sassModuleIndex, 0, lessModule);
```

**Comment by digz6666** [comment]
Can I import less in component like this?
