### ISSUE TITLE
[Question] Does your plugin work with @ant-design?

### ISSUE THREAD

**Issue by w20k** [SolidZORO/next-plugin-antd-less#10]
Hello,

Really great plugin to begin with antd and less. Quick question, do you know a way how to add support for @ant-design (layouts, tables, fields, utils & etc)? 
Having quite a lot of issues (errors & warning) with that right now (SyntaxError: Unexpected token 'export', ./index.less error and more).

Thanks for the tips, if you have any!

**Comment by SolidZORO** [comment]
you can try current version 0.1.3, it's support Next.js v10.
