### ISSUE TITLE
Support ant-mobile

### ISSUE THREAD

**Issue by A-Vershinin** [SolidZORO/next-plugin-antd-less#101]
Does this plugin support ant-mobile package? The mobile version of ant also has `less` version of styles.
Could you provide some example how to use this plugin for it?

**Comment by SolidZORO** [comment]
Waiting for the official release and official support for NextJS.

**Comment by SolidZORO** [comment]
@A-Vershinin https://github.com/ant-design/ant-design-mobile/issues/4643

**Comment by SolidZORO** [comment]
@A-Vershinin
