### ISSUE TITLE
Invalid next.config.js options detected

### ISSUE THREAD

**Issue by 1742014** [SolidZORO/next-plugin-antd-less#106]
i got warn message when start project nextjs

<img width="565" alt="Screen Shot 2022-08-03 at 11 17 29" src="https://user-images.githubusercontent.com/24929517/182523074-4fbaca24-4427-4024-bd26-4957fdfb4fbc.png">

- Nextjs version: 12.2.3
- next-plugin-antd-less version: 1.8.0
- Node version: 16.6.0

**Comment by 1742014** [comment]
dulicate #105

**Comment by 1742014** [comment]
duplicate #105

**Comment by noopurphalak** [comment]
@1742014 What was the issue, how did you resolve it?
