### ISSUE TITLE
How to make it work with @ant-design/pro-layout

### ISSUE THREAD

**Issue by darwis059** [SolidZORO/next-plugin-antd-less#23]
I am trying to add `@ant-design/pro-layout` to my nextjs project. its working on development with lazy import pro-layout component. but pro layout style is missing on production.

```
/home/darwis/dev/next-exmpl/with-type-script-app/node_modules/antd/es/layout/style/index.js:1
import '../../style/index.less';
       ^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
```

**Comment by dzcpy** [comment]
Any solutions?

**Comment by SolidZORO** [comment]
@darwis059  can you give me a demo repo to test?
