### ISSUE TITLE
How to prevent overriding the rules defined in global.scss

### ISSUE THREAD

**Issue by legenddaniel** [SolidZORO/next-plugin-antd-less#25]
Hi SolidZORO,

Thank you for your great plugin. I have changed the default variables but my styles defined in global.scss are overrided by the re-compiled antd styles. Before it was overriding the default antd styles.

It means new-antd.less > global.scss > antd.less.

Is there any way to avoid this?

**Comment by SolidZORO** [comment]
maybe you can write a node batch js file, every run `yarn dev`, hook this js, copy all new-antd.less (vars) > global.scss.
