### ISSUE TITLE
Inline JavaScript is not enabled. Is it set in your options? [How to enable this in config?]

### ISSUE THREAD

**Issue by hridoy43** [SolidZORO/next-plugin-antd-less#26]
Getting this error when building nexjs app with **yarn build** command, After configuring as u mentioned in doc. 

**Error-Log:**

error - ./node_modules/antd/lib/button/style/index.less ((webpack)/css-loader/cjs.js??ref--5-oneOf-3-1!(webpack)/postcss-loader/cjs.js??ref--5-oneOf-3-2!(webpack)/resolve-url-loader??ref--5-oneOf-3-3!./node_modules/less-loader/dist/cjs.js??ref--5-oneOf-3-4!./node_modules/antd/lib/button/style/index.less)

// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
**Inline JavaScript is not enabled. Is it set in your options?**
      in /Volumes/Mac-Util/Projects/thrive/vidar/node_modules/antd/lib/style/color/bezierEasing.less (line 110, column 0)
      
**nextjs.config.js:**      
`const withAntdLess = require('next-plugin-antd-less');
module.exports = withAntdLess({
    javascriptEnabled: true,
    modifyVars: { '@primary-color': 'red' },
    lessVarsFilePath: './styles/antd_theme.less',
    cssLoaderOptions: {},
    webpack(config) {
        return config;
    },
}); `

**Comment by daniboomerang** [comment]
Same here

**Comment by daniboomerang** [comment]
Ok. @hridoy43 Fixed it by removing all old installed dependencies I had that were being used by `next-plugin-antd-less`
So I removed from my package.json
``` 
  "@zeit/next-less": "^1.0.1",
  "null-loader": "2.0.0",
  "less": "3.0.4",
  "less-vars-to-js": "1.3.0",
```
