### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by dpyzo0o** [SolidZORO/next-plugin-antd-less#3]
我看到你在这里配置了这个属性，我看了css-loader的文档，还是不太明白这个配置有什么用？我试着不设置这个属性，看起来好像也没什么问题

  https://github.com/SolidZORO/next-plugin-antd-less/blob/757f8df159242a5b772eba0ada225a0dd2260899/index.js#L84

希望得到解答，谢谢！

**Comment by SolidZORO** [comment]
这几天在岛上生活，没用电脑，回复晚了。

https://webpack.docschina.org/loaders/css-loader/#exportglobals 这里有中文说明。

不过具体为什么加上我也忘了，可能是我需要比如 

```
a.module.less

:global(.@{THEME--DARK}) {
  button.timer {
    color: var(--primary-color);
  }
}
```

这种写法的时候能正常导出的时候设置了。不过没具体研究，如果不需要可以先 fork 去掉，待我弄明白了再过来这边 comment。
