### ISSUE TITLE
Feature: Can I add  sideEffects = true ?

### ISSUE THREAD

**Issue by loyep** [SolidZORO/next-plugin-antd-less#34]
```
  // clone
  const lessModule = clone(sassModule);
  lessModule.test = /\.less$/;
  delete lessModule.issuer;
  lessModule.sideEffects = true;
```

`sideEffect` can make use import not require the global less.

**Comment by SolidZORO** [comment]
you say tree-shaking?

**Comment by SolidZORO** [comment]
You can control the sideEffects in the project's package.json and should not control them in the loader. If you want to import "global" styles, just use the abc.less name, not abc.module.less. Or use this in abc.module.less

```less
.xyz { }

:global(.abc) { } // <---- global style
```
