### ISSUE TITLE
Inline JavaScript is not enabled

### ISSUE THREAD

**Issue by llamadeus** [SolidZORO/next-plugin-antd-less#4]
I'm getting the following error when using your package.
```error - ./node_modules/antd/lib/style/index.less (./node_modules/next/node_modules/css-loader/dist/cjs.js??ref--5-oneOf-3-1!./node_modules/next/dist/compiled/postcss-loader??__nextjs_postcss!./node_modules/resolve-url-loader??ref--5-oneOf-3-3!./node_modules/less-loader/dist/cjs.js??ref--5-oneOf-3-4!./node_modules/antd/lib/style/index.less)

// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      in node_modules/antd/lib/style/color/bezierEasing.less (line 110, column 0)
```

I have found out that `javascriptEnabled` is being set to true in the following snippet but the option is erroneously nested within the `lessOptions` object.
```
const lessLoaderIndex = lessModule.use.findIndex((item) => `${item.loader}`.includes('sass-loader'));
lessModule.use.splice(lessLoaderIndex, 1, {
  loader: 'less-loader',
  options: {
    lessOptions: {
      javascriptEnabled: true,
      modifyVars,
    },
  },
});
```

Instead the options should be set to true like this:
```
const lessLoaderIndex = lessModule.use.findIndex((item) => `${item.loader}`.includes('sass-loader'));
lessModule.use.splice(lessLoaderIndex, 1, {
  loader: 'less-loader',
  options: {
    javascriptEnabled: true,
    modifyVars,
  },
});
```

**Comment by SolidZORO** [comment]
https://github.com/SolidZORO/next-plugin-antd-less/blob/757f8df159242a5b772eba0ada225a0dd2260899/index.js#L68

**Comment by llamadeus** [comment]
> https://github.com/SolidZORO/next-plugin-antd-less/blob/757f8df159242a5b772eba0ada225a0dd2260899/index.js#L68

I can see that `javascriptEnabled` is being set to true but it still does not work because the option should not be set to true within the `lessOptions` object but directly within the `options` object.

**Comment by SolidZORO** [comment]
this is less-loader  BREAKING CHANGES.

https://github.com/webpack-contrib/less-loader/blob/master/CHANGELOG.md#600-2020-04-24

https://github.com/webpack-contrib/less-loader#lessoptions

if your still not work, pls update less-loader version to v6.0.0+.

**Comment by llamadeus** [comment]
Thanks! I found the root of the problem. Having your plugin installed along with `@zeit/next-less` caused two versions of `less-loader` being installed: 4.x and 6.x. Uninstalling `@zeit/next-less` solved the issue for me.

Also, thanks for this plugin! I really appreciate it.
