### ISSUE TITLE
I need to config sass module regx

### ISSUE THREAD

**Issue by Kongnut** [SolidZORO/next-plugin-antd-less#49]
I need to config sass module regx, right now it is *.module.*(css) pattern, but I would like to pass an option to it (default remain the same)

I already create a PR for this thing. 
[https://github.com/SolidZORO/next-plugin-antd-less/pull/48]

**Comment by SolidZORO** [comment]
Hi, I just saw your PR, thanks for your involvement. but this plugin only handles `antd` and `less` configuration. If you need it, please fork a copy to use it.
