### ISSUE TITLE
dynamic variables

### ISSUE THREAD

**Issue by amirjr1378** [SolidZORO/next-plugin-antd-less#50]
i have to change my palette base on request , with latest less in window we have less.modifyVars({
  '@bgColor': 'blue',
  '@textColor': 'red'
});

but i dont have it when i use this package

**Comment by SolidZORO** [comment]
request?

Once the content of modifyVars is set, it cannot be changed except by restarting the server.

If you want to change it dynamically, modify the .less file, or append style to the end of the body.

**Comment by amirjr1378** [comment]
by request means api , i get palette from api

**Comment by amirjr1378** [comment]
how can i modify .less file dynamically?

**Comment by SolidZORO** [comment]
get api data, and append to html body. data be a <style> tag.

**Comment by amirjr1378** [comment]
> get api data, and append to html body. data be a <style> tag.

i know , but it is not possible to change less var like @primary style tag or in css in general.

**Comment by SolidZORO** [comment]
I usually use script `https://github.com/SolidZORO/mkn/blob/master/src/styles/_sync-vars-to-root.js` sync all `less vars` to `css vars `https://github.com/SolidZORO/mkn/blob/master/src/styles/variables-css.less`, that I can change var in the project via `css vars` by `:root {}`.
