### ISSUE TITLE
Exception in webpack while loading next-plugin-antd-less externals

### ISSUE THREAD

**Issue by nishant-dani** [SolidZORO/next-plugin-antd-less#55]
While trying to following the instructions to debug the nextjs app using --inspect and chrome://inspect the debugger breaks at this exception.  I tracked it to external handling in the webpack config for next-plugin-antd-less.  Would you have any tips on how to move forward or workaround this?

{
    "code": "MODULE_NOT_FOUND",
    "requireStack": [
        "/../node_modules/next/dist/build/webpack-config.js",
        "/../node_modules/next/dist/server/hot-reloader.js",
        "/../node_modules/next/dist/server/next-dev-server.js",
        "/../node_modules/next/dist/server/next.js",
        "/../node_modules/next/dist/server/lib/start-server.js",
        "/../node_modules/next/dist/cli/next-dev.js",
        "/../node_modules/next/dist/bin/next"
    ]
}

Cannot find module 'next-plugin-loader?middleware=on-init-server!'

Error: Cannot find module 'next-plugin-loader?middleware=on-init-server!'
"Error: Cannot find module 'next-plugin-loader?middleware=on-init-server!'
Require stack:
- /yeticlient/node_modules/next/dist/build/webpack-config.js
- /yeticlient/node_modules/next/dist/server/hot-reloader.js
- /yeticlient/node_modules/next/dist/server/next-dev-server.js
- /yeticlient/node_modules/next/dist/server/next.js
- /yeticlient/node_modules/next/dist/server/lib/start-server.js
- /yeticlient/node_modules/next/dist/cli/next-dev.js
- /yeticlient/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.mod._resolveFilename (/yeticlient/node_modules/next/dist/build/webpack/require-hook.js:4:1784)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)
    at /yeticlient/node_modules/next/dist/build/webpack-config.js:82:257
    at new Promise (<anonymous>)
    at /yeticlient/node_modules/next/dist/build/webpack-config.js:82:220
    at handleExternals (/yeticlient/node_modules/next/dist/build/webpack-config.js:51:23)
    at Array.webpackConfig.externals (/yeticlient/node_modules/next/dist/build/webpack-config.js:82:149)
    **_**at webpackConfig.externals (/yeticlient/node_modules/next-plugin-antd-less/overrideWebpackConfig.js:311:62)**_**
    at handleExternals (/yeticlient/node_modules/next/dist/compiled/webpack/bundle4.js:57292:17)
    at next (/yeticlient/node_modules/next/dist/compiled/webpack/bundle4.js:57280:9)
    at handleExternals (/yeticlient/node_modules/next/dist/compiled/webpack/bundle4.js:57285:7)
    at /yeticlient/node_modules/next/dist/compiled/webpack/bundle4.js:57315:5
    at /yeticlient/node_modules/next/dist/compiled/webpack/bundle4.js:64070:5
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/yeticlient/node_modules/next/dist/compiled/webpack/bundle4.js:43435:10), <anonymous>:4:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook (/yeticlient/node_modules/next/dist/compiled/webpack/bundle4.js:43372:20)"

In package.json, use this script:
    "debug": "NODE_OPTIONS='--inspect=0.0.0.0:9229' next dev",

Attach to the application with chrome://inspect

This is line 311 on the code;

```
[                                                                                                           
          // webpack4                                                                                               
          (ctx, req, cb) => {                                                                                       
            if (req.match(ANTD_STYLE_REGX)) return cb();                                                            
                                                                                                                    
            if (typeof exts[0] === 'function') return exts[0](ctx, req, cb);        -- LINE 311                                
            else return cb();                                               
          },                                                                
          ...(typeof exts[0] === 'function' ? [] : exts),                    
        ];                                        
```

**Comment by SolidZORO** [comment]
This feels too complicated for me to read 😂.

**Comment by nishant-dani** [comment]
Sorry about the complex description.  However, this got resolved by updating to the latest nextjs "next": "^10.2.0".  Will keep tracking to see if it recurs.
