### ISSUE TITLE
Enable CSS Support for Component-Level Styles

### ISSUE THREAD

**Issue by samkahchiin** [SolidZORO/next-plugin-antd-less#58]
My component is generated dynamically based on the user selection, therefore,
I would like to enable CSS Support for Component-Level Styles instead of CSS Module Support.

Is it possible to do this in `next-plugin-antd-less`?
Thanks.

**Comment by SolidZORO** [comment]
you can see:

https://github.com/SolidZORO/mkn/blob/5fd9609230532978600ec8a7d4113ca3b9f3a5f7/src/page-components/test/Test/Test.tsx#L9-L25
