### ISSUE TITLE
next.js 10.2.3 breaking woff loader

### ISSUE THREAD

**Issue by sitch** [SolidZORO/next-plugin-antd-less#60]
Had to revert to my previous PR due to an issue only present when building with `target: 'serverless'` and importing a `.woff` font.  Seems to be a loader issue

**Comment by SolidZORO** [comment]
next.js update does not comply with the [standard-version](https://github.com/conventional-changelog/standard-version) specification at all, even a small version upgrade will have a lot of **BREAK CHANGE**, so I do not intend to fix immediately, wait for their official solution less CSS problem. I'm tired.

**Comment by SolidZORO** [comment]
If you want to use this plugin on next.js, please make sure you have version <= 10.2.0.

**Comment by sitch** [comment]
Noted -- Thanks so much for the help to date!
