### ISSUE TITLE
lessVarsFilePath not being used after updating from 0.3.0 to 1.3.0 on Next 11

### ISSUE THREAD

**Issue by deschantkn** [SolidZORO/next-plugin-antd-less#69]
I have a less file in my Next.js project that I am referencing like this: 

```
const moduleExports = withAntdLess({
  lessVarsFilePath: './assets/styles/variables.less',
  // optional https://github.com/webpack-contrib/css-loader#object
  cssLoaderOptions: {},
  webpack(config, options) {
    config.module.rules.push({
      test: /\.svg$/,
      use: ['@svgr/webpack'],
    });

    return config;
  },
});
```

This was working before updating but is now having no effect after udpating. Am I missing something?
Using the `modifyVars` property works but isn't ideal for me.

UPDATE: I am using `antd@4.15.6`

**Comment by SolidZORO** [comment]
try https://github.com/SolidZORO/next-plugin-antd-less/issues/52#issuecomment-834030062
