### ISSUE TITLE
How to avoid modifying global styles?

### ISSUE THREAD

**Issue by salihozdemir** [SolidZORO/next-plugin-antd-less#8]
If i need to integrate ant-design as a part of an existing website, it's likely i want to prevent ant-design to override global styles. How can i do this?

![image](https://user-images.githubusercontent.com/41580619/95512994-49b77f80-09c2-11eb-8aa7-5a64ec6c4ba7.png)

Can we prevent global.less from loading?

**Comment by SolidZORO** [comment]
what file is this `global.less`? Is it from `antd`?

**Comment by salihozdemir** [comment]
Yes it comes from antd. I couldn't find a solution other than overriding.

**Comment by SolidZORO** [comment]
you can try 

``` 
// .babelrc.js

plugins: [
    [
      'import',
      {
        libraryName: 'antd',
        // style: true,   <--- remove this line
      },
    ]
  ],
```

and create `antd-reset.less`, like this:

```less
/* stylelint-disable at-rule-no-unknown */
@import './animate.less';

@import '~antd/es/style/themes/index.less';
//@import '~antd/es/style/core/index.less';

@import '~antd/es/style/mixins/index.less';
//@import '~antd/es/style/core/base.less';
//@import '~antd/es/style/core/iconfont.less';
@import '~antd/es/style/core/motion.less';

//@import '~antd/es/grid/style/index.less';
//@import '~antd/es/icon/style/index.less';
@import '~antd/es/modal/style/index.less';
@import '~antd/es/button/style/index.less';
@import '~antd/es/input/style/index.less';
@import '~antd/es/switch/style/index.less';
@import '~antd/es/form/style/index.less';
@import '~antd/es/upload/style/index.less';
@import '~antd/es/message/style/index.less';
//@import '~antd/es/auto-complete/style/index.less';
@import '~antd/es/select/style/index.less';
@import '~antd/es/date-picker/style/index.less';

```

**Comment by salihozdemir** [comment]
I created the reset-antd.less  then imported it in _appjs. It's work perfectly yarn dev but when i build my project styles of ant components are not loaded. 
Is the less format in app.js the problem or is it adding a css globally?
What should I do? I just couldn't find.

**Comment by 15520065** [comment]
@salihozdemir Have you find the solution yet?
