### ISSUE TITLE
How to enable the dark mode?

### ISSUE THREAD

**Issue by THPubs** [SolidZORO/next-plugin-antd-less#80]
Hi, I tried adding the following to `modifyVars ` but it still didn't work. Any idea what's happening?

```
'@THEME--DARK': 'theme-dark',
dark: true
```

**Comment by SolidZORO** [comment]
😂 All this code needs to be written by you, the plugin does not provide dark mode.

**Comment by THPubs** [comment]
@SolidZORO  But Antd does have an official dark mode theme ([](https://ant.design/docs/react/customize-theme#Use-dark-or-compact-theme)). I'm trying to enable that. Once it got loaded but with a reload it went back to the default theme.

**Comment by THPubs** [comment]
@SolidZORO Found out how to do it!

```javascript
const { getThemeVariables } = require('antd/dist/theme');

...

  modifyVars: {
    ...getThemeVariables({
      dark: true, // Enable dark mode
    }),
    '@primary-color': '#ffffff',
  },
  javascriptEnabled: true,
```

You have to wrap the config with `getThemeVariables` and set `javascriptEnabled` to `true`.
