### ISSUE TITLE
Extremely slow build and hot reload times with Next.js

### ISSUE THREAD

**Issue by newtonmunene99** [SolidZORO/next-plugin-antd-less#85]
Sorry, I know this might be a duplicate of #75 but I don't really think that issue was resolved. 
When I use this plugin the hot reload are incredibly slow, sometimes even 3 - 5 minutes.  
Using the plugin isn't nearly productive. I'm spending 70% percent of my time waiting for the hot reloads and only 30% actually writing code. 

Do we have any way of optimizing this? Any recommendations?

Here's my `next.config.js`

```js
const withAntdLess = require("next-plugin-antd-less");

module.exports = withAntdLess({
  lessVarsFilePath: "./src/styles/variables.less",
  reactStrictMode: true,
  webpack(config) {
    return config;
  },
});
```

And `.babelrc.js`

```js
// .babelrc.js
module.exports = {
  presets: [["next/babel"]],
  plugins: [["import", { libraryName: "antd", style: true }]],
};
```

**Comment by SolidZORO** [comment]
@newtonmunene99 Is it solved?

**Comment by newtonmunene99** [comment]
@SolidZORO I'm seeing a significant improvement in the hot reload times. Initial build times still a bit slow but it's tolerable now.
Thanks
