### ISSUE TITLE
Plugin not working on windows (works fine on linux)

### ISSUE THREAD

**Issue by yxx4c** [SolidZORO/next-plugin-antd-less#86]
The plugin works fine on linux but fails to work on windows. There are no errors what so ever, but the changes made in variables.less are not reflected when in windows env.

Sample code: https://github.com/yxx4c/-next-plugin-antd-less-issue-86

**Comment by SolidZORO** [comment]
@yxx4c sorry, i not have a windows PC. Is it solved?

**Comment by yxx4c** [comment]
@SolidZORO It's not resolved yet, I'm using some alternative methods to do it manually after every change and generate a static css file. If you could look into it, it would be a huge help, I can provide as much information as you need. Thank you for the awesome project and the time you took to respond to the issue 😊

**Comment by SolidZORO** [comment]
It seems to be a windows problem, you can go to the nextjs issues to ask.

**Comment by sgillespie** [comment]
I've been able to get this working on Windows, but my setup is a little different:
```
// Where your antd-custom.less file lives
const themeVariables = lessToJS(
  fs.readFileSync(path.resolve(__dirname, './src/styles/antd-custom.less'), 'utf8')
);

module.exports = withAntdLess({
  // <-- Snip -->
  lessLoaderOptions: {
    lessOptions: {
      javascriptEnabled: true,
      modifyVars: themeVariables // make our antd custom effective
    },
// <-- Snip -->
});
