### ISSUE TITLE
Next.js 12 support

### ISSUE THREAD

**Issue by timothymiller** [SolidZORO/next-plugin-antd-less#87]
# Feature Request

This module should support the latest version of Next.js version 12, along with support for the new SWC integration.

https://nextjs.org/blog/next-12#faster-builds-and-fast-refresh-with-rust-compiler

**Comment by SolidZORO** [comment]
I just updated 1.5.1 to be compatible with Next.js 12. more see [CHANGELOG](https://github.com/SolidZORO/next-plugin-antd-less/blob/master/CHANGELOG.md#150-2021-11-01).
