### ISSUE TITLE
Next.js 12 import less file error

### ISSUE THREAD

**Issue by tigressbailey** [SolidZORO/next-plugin-antd-less#88]
After updated to Next.js 12
`import styles from './Container.module.less'` will report an error:

<img width="1023" alt="Screen Shot 2021-10-28 at 11 52 04 AM" src="https://user-images.githubusercontent.com/15047538/139183690-759dae20-bb74-4be5-817e-0470cf43b450.png">

Config is:
```JavaScript
 ...withAntdLess({
        // optional
        lessVarsFilePath: './styles/variable.less',
        // optional
        lessVarsFilePathAppendToEndOfContent: true,
        lessLoaderOptions: {
          lessOptions: {
            javascriptEnabled: true,
            math: 'always',
          },
        },

        // Other Config Here...
        webpack(config, options) {
          return config
        },
      }),
```

**Comment by SolidZORO** [comment]
I just updated 1.5.1 to be compatible with Next.js 12. more see [CHANGELOG](https://github.com/SolidZORO/next-plugin-antd-less/blob/master/CHANGELOG.md#150-2021-11-01).
