### ISSUE TITLE
导出静态html，antd 样式可以，css可以，自定义的less没有样式？求解

### ISSUE THREAD

**Issue by tanwei0425** [SolidZORO/next-plugin-antd-less#9]
![image](https://user-images.githubusercontent.com/37789693/96232162-7d019c00-0fca-11eb-8d98-f1012883a58a.png)
next.config.js配置

**Comment by SolidZORO** [comment]
lessVarsFilePath 里面的 antd.less 文件格式是变量，比如：

```less
@primary-color: #d61a1b;
@primary-color--dark: #fff;
```

你想要实现什么？覆盖 antd 的 样式？

**Comment by tanwei0425** [comment]
@SolidZORO 我的意识 antd 都好使，包括自定义主题。。。。但是其余自己写的less      yarn dev 启动没问题，yarn build后yarn start 打完包之后 没有样式
