### ISSUE TITLE
(Question) Possible to drop babel to use SWC + NextJS 12

### ISSUE THREAD

**Issue by timothymiller** [SolidZORO/next-plugin-antd-less#93]
The `babel.config.json` file is preventing next.js from using the new SWC features.

We all would love to see build times decrease. Is it possible to support ant design without babel?

**Comment by SolidZORO** [comment]
Wait for nextjs13 to see again.

**Comment by timothymiller** [comment]
> Wait for nextjs13 to see again.

I don't understand. What does nextjs13 have to do with supporting SWC like the [README.md](https://github.com/SolidZORO/next-plugin-antd-less/issues/93) clearly states in the compatibility section?
