### ISSUE TITLE
README.md incorrectly lists SWC support

### ISSUE THREAD

**Issue by timothymiller** [SolidZORO/next-plugin-antd-less#94]
# The [README.md](https://github.com/SolidZORO/next-plugin-antd-less#-compatibility) clearly lists SWC support in the compatibility section.

## This conflicts with your statement from #93

> Wait for nextjs13 to see again.

## I don't understand. What does nextjs13 have to do with supporting SWC like the README.md clearly states in the compatibility section?

**Comment by SolidZORO** [comment]
I mean wait until SWC for NextJS is stable, it looks like they will be stable in 13 or 14 and will need to be configured to support babel. 

wait until then this plugin will be rewritten in the SWC loader way.

**Comment by fuyucn** [comment]
> I mean wait until SWC for NextJS is stable, it looks like they will be stable in 13 or 14 and will need to be configured to support babel.
> 
> wait until then this plugin will be rewritten in the SWC loader way.

If using babel.config.js will cause Next.js disable SWC support, then this plugin is not support SWC.
