### ISSUE TITLE
Module not found: Can't resolve './data:image/svg+xml;

### ISSUE THREAD

**Issue by zhanghecool** [SolidZORO/next-plugin-antd-less#97]
![企业微信20211119-154001](https://user-images.githubusercontent.com/7930156/142585583-d1bf176b-4939-4f89-8215-e80a78852d8b.png)

I use AntD Pro for development.
It cannot read the data in background-image:url (data:image).

thanks.

**Comment by SolidZORO** [comment]
similar https://github.com/SolidZORO/next-plugin-antd-less/issues/96
