### ISSUE TITLE
Error evaluating function `ceil`: argument must be a number

### ISSUE THREAD

**Issue by mtahagocer** [SolidZORO/next-plugin-antd-less#99]
I'm using antd with nextjs. And following error occured on only docker. When I build manually on windows build getting success. 

dependencies

`
{
"antd": "4.16.13",
"next": "12.0.2",
"next-plugin-antd-less": "1.5.2",
}
`

Here is my configs.
```
  lessVarsFilePath: './styles/variables.less',

  lessLoaderOptions: {

 lessOptions: {
      strictMath: false,
      math: 'always',
      javascriptEnabled: true
    }

  },
```

@SolidZORO can u help?

Here is the error log

` > [build_image 6/8] RUN yarn build:
#15 0.461 yarn run v1.22.15
#15 0.501 $ cross-env NODE_ENV=production NODE_OPTIONS=--openssl-legacy-provider next build
#15 0.981 info  - Loaded env from /app/.env.production
#15 1.412 Attention: Next.js now collects completely anonymous telemetry regarding usage.
#15 1.412 This information is used to shape Next.js' roadmap and prioritize features.
#15 1.412 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#15 1.412 https://nextjs.org/telemetry
#15 1.412
#15 1.570 info  - Checking validity of types...
#15 8.043 warn  - The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
#15 9.347 info  - Creating an optimized production build...
#15 9.386 warn  - Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.js" https://nextjs.org/docs/messages/swc-disabled
#15 10.15 info  - Using external babel configuration from /app/babel.config.js
#15 37.52 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/styles/theme.less': No serializer registered for LessError
#15 37.52 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.53 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/src/modules/iso-rto-market-data/LmpMonthly/PricePattern/index.less': No serializer registered for LessError
#15 37.53 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.53 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/src/modules/login/styles/login.module.less': No serializer registered for LessError
#15 37.53 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.55 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/node_modules/antd/lib/config-provider/style/index.less': No serializer registered for LessError
#15 37.55 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.55 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/node_modules/antd/lib/style/index.less': No serializer registered for LessError
#15 37.55 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.55 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/node_modules/antd/lib/input/style/index.less': No serializer registered for LessError
#15 37.55 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.56 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/node_modules/antd/lib/select/style/index.less': No serializer registered for LessError
#15 37.56 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.56 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/node_modules/antd/lib/checkbox/style/index.less': No serializer registered for LessError
#15 37.56 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.56 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/node_modules/antd/lib/form/style/index.less': No serializer registered for LessError
#15 37.56 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.56 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/node_modules/antd/lib/image/style/index.less': No serializer registered for LessError
#15 37.56 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.57 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/node_modules/antd/lib/layout/style/index.less': No serializer registered for LessError
#15 37.57 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.58 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/src/components/Layouts/Sidebar/index.less': No serializer registered for LessError
#15 37.58 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.58 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/src/components/Layouts/Navbar/index.module.less': No serializer registered for LessError
#15 37.58 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.58 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/src/components/Layouts/Footer/index.module.less': No serializer registered for LessError
#15 37.58 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.58 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/src/components/base/ChartCard/index.less': No serializer registered for LessError
#15 37.58 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.58 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/node_modules/antd/lib/button/style/index.less': No serializer registered for LessError
#15 37.58 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.59 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/common/Providers/BackdropProvider/index.less': No serializer registered for LessError
#15 37.59 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.59 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/node_modules/antd/lib/empty/style/index.less': No serializer registered for LessError
#15 37.59 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.59 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/node_modules/antd/lib/tooltip/style/index.less': No serializer registered for LessError
#15 37.59 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.59 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/node_modules/antd/lib/grid/style/index.less': No serializer registered for LessError
#15 37.59 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.61 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/node_modules/antd/lib/menu/style/index.less': No serializer registered for LessError
#15 37.61 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.62 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/node_modules/antd/lib/notification/style/index.less': No serializer registered for LessError
#15 37.62 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.62 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/node_modules/antd/lib/modal/style/index.less': No serializer registered for LessError
#15 37.62 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.62 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/src/asseths/svg/Vector/index.less': No serializer registered for LessError
#15 37.62 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 37.63 <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/app/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!/app/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!/app/node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!/app/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!/app/node_modules/antd/lib/divider/style/index.less': No serializer registered for LessError
#15 37.63 <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> LessError
#15 39.03 Failed to compile.
#15 39.03
#15 39.03 ./common/Providers/BackdropProvider/index.less.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!./node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!./node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!./common/Providers/BackdropProvider/index.less
#15 39.03
#15 39.03 @font-size-sm: 12px;
#15 39.03 @heading-1-size: ceil(@font-size-base * 2.71);
#15 39.03                ^
#15 39.03 Error evaluating function `ceil`: argument must be a number
#15 39.03       Error in /app/node_modules/antd/lib/style/themes/default.less (line 67, column 17)
#15 39.03
#15 39.03 Import trace for requested module:
#15 39.03 ./common/Providers/BackdropProvider/index.less
#15 39.03 ./common/Providers/BackdropProvider/index.tsx
#15 39.03 ./common/Providers/CommonProvider.tsx
#15 39.03 ./src/providers/RootProvider.tsx
#15 39.03 ./pages/_app.tsx
#15 39.03
#15 39.03 ./node_modules/antd/lib/button/style/index.less.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!./node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!./node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!./node_modules/antd/lib/button/style/index.less
#15 39.03
#15 39.03 @font-size-sm: 12px;
#15 39.03 @heading-1-size: ceil(@font-size-base * 2.71);
#15 39.03                ^
#15 39.03 Error evaluating function `ceil`: argument must be a number
#15 39.03       Error in /app/node_modules/antd/lib/style/themes/default.less (line 67, column 17)
#15 39.03
#15 39.03 Import trace for requested module:
#15 39.03 ./node_modules/antd/lib/button/style/index.less
#15 39.03 ./node_modules/antd/lib/button/style/index.js
#15 39.03 ./node_modules/antd/lib/input/style/index.js
#15 39.03 ./src/modules/login/components/index.tsx
#15 39.03 ./pages/index.tsx
#15 39.03
#15 39.03 ./node_modules/antd/lib/checkbox/style/index.less.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!./node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!./node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!./node_modules/antd/lib/checkbox/style/index.less
#15 39.03
#15 39.03 @font-size-sm: 12px;
#15 39.03 @heading-1-size: ceil(@font-size-base * 2.71);
#15 39.03                ^
#15 39.03 Error evaluating function `ceil`: argument must be a number
#15 39.03       Error in /app/node_modules/antd/lib/style/themes/default.less (line 67, column 17)
#15 39.03
#15 39.03 Import trace for requested module:
#15 39.03 ./node_modules/antd/lib/checkbox/style/index.less
#15 39.03 ./node_modules/antd/lib/checkbox/style/index.js
#15 39.03 ./src/modules/login/components/index.tsx
#15 39.03 ./pages/index.tsx
#15 39.03
#15 39.03 ./node_modules/antd/lib/config-provider/style/index.less.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!./node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!./node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!./node_modules/antd/lib/config-provider/style/index.less
#15 39.03
#15 39.03 @font-size-sm: 12px;
#15 39.03 @heading-1-size: ceil(@font-size-base * 2.71);
#15 39.03                ^
#15 39.03 Error evaluating function `ceil`: argument must be a number
#15 39.03       Error in /app/node_modules/antd/lib/style/themes/default.less (line 67, column 17)
#15 39.03
#15 39.03 Import trace for requested module:
#15 39.03 ./node_modules/antd/lib/config-provider/style/index.less
#15 39.03 ./node_modules/antd/lib/config-provider/style/index.js
#15 39.03 ./src/providers/RootProvider.tsx
#15 39.03 ./pages/_app.tsx
#15 39.03
#15 39.03 ./node_modules/antd/lib/divider/style/index.less.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[6].use[2]!./node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[6].use[3]!./node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[6].use[4]!./node_modules/antd/lib/divider/style/index.less
#15 39.03
#15 39.03 @font-size-sm: 12px;
#15 39.03 @heading-1-size: ceil(@font-size-base * 2.71);
#15 39.03                ^
#15 39.03 Error evaluating function `ceil`: argument must be a number
#15 39.03       Error in /app/node_modules/antd/lib/style/themes/default.less (line 67, column 17)
#15 39.03
#15 39.03 Import trace for requested module:
#15 39.03 ./node_modules/antd/lib/divider/style/index.less
#15 39.03 ./node_modules/antd/lib/divider/style/index.js
#15 39.03 ./src/components/base/ChartCard/index.tsx
#15 39.03 ./src/modules/iso-rto-market-data/LmpMonthly/PricePattern/index.tsx
#15 39.03 ./src/modules/iso-rto-market-data/LmpMonthly/index.tsx
#15 39.03 ./pages/home.tsx
#15 39.03
#15 39.03
#15 39.03 > Build failed because of webpack errors
#15 39.08 error Command failed with exit code 1.
#15 39.08 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
executor failed running [/bin/sh -c yarn build]: exit code: 1`

**Comment by SolidZORO** [comment]
This looks pretty scary and I can't help you.

**Comment by mtahagocer** [comment]
> This looks pretty scary and I can't help you.

So, is it possible it's because of linux?
